parameters:
  imageId:
    in: path
    name: id
    schema:
      type: integer
    required: true
    description: ID of the image to get

  imageFile:
    in: formData
    name: uploadFile
    type: file
    required: true
    description: The image file to upload

  imageEncrypted:
    in: formData
    name: encrypted
    type: boolean
    required: false
    description: Whether or not the currently uploading image is encrypted